// Generated by CoffeeScript 1.3.3

global.config = {
  LOG_LEVEL: "info",
  LISTEN_PORT: 5985
};

global._ = require('underscore');

global.async = require('async');

global.Step = require('step');

global.FutonServer = require('./futon_server');

global.logger = new (require('./logger'))("redis_futon");

if (String.prototype.chomp == null) {
  String.prototype.chomp = function() {
    return this.replace(/(\n|\r)+$/, '');
  };
}

if (String.prototype.strip == null) {
  String.prototype.strip = String.prototype.trim;
}

if (String.prototype.contains == null) {
  String.prototype.contains = function(partial) {
    return this.indexOf(partial) !== -1;
  };
}
