// Generated by CoffeeScript 1.3.3
var MainController, RedisInterface;

RedisInterface = require('./redis_interface');

MainController = (function() {

  function MainController() {
    this.redis = new RedisInterface();
    this.routes = [
      {
        path: "/redis/info",
        http_method: "get",
        method: "redis_info"
      }
    ];
    return;
  }

  MainController.prototype.redis_info = function(req, res) {
    return this.redis.info(function(err, resp) {
      return res.json(resp);
    });
  };

  return MainController;

})();

module.exports = MainController;
