// Generated by CoffeeScript 1.3.3
var MainController, RedisInterface;

RedisInterface = require('./redis_interface');

MainController = (function() {

  function MainController() {
    this.redis = new RedisInterface();
  }

  MainController.prototype.info = function(req, res) {
    return this.redis.info(function(err, resp) {
      return res.json({
        app: "Redis Futon",
        version: "0.0.1",
        server_info: resp
      });
    });
  };

  return MainController;

})();

module.exports = MainController;
