// Generated by CoffeeScript 1.3.3
var RedisInterface, redis;

redis = require("redis");

RedisInterface = (function() {

  function RedisInterface(host, port) {
    this.host = host != null ? host : 'localhost';
    this.port = port != null ? port : 6379;
    this.client = redis.createClient(this.port, this.host);
    this.client.on("error", function(err) {
      return logger.error("Redis Error", err);
    });
  }

  RedisInterface.prototype.info = function(callback) {
    return this.client.info(function(err, resp) {
      return callback(err, resp);
    });
  };

  return RedisInterface;

})();

module.exports = RedisInterface;
